spring.application.name=greencycle

# Configuration Base de données MariaDB
spring.datasource.url=jdbc:mariadb://mysql-oats.alwaysdata.net/oats_greencycle_db
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.datasource.username=oats_safe_green
spring.datasource.password=greengreen1%GREEN
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#---ONLY IN DEV MODE------------------------------------------------------------------------------------------
# Console H2 (accessible via /h2-console)
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#-----------------------------------------------------------------------------------------------------------

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret (A changer en prod)
jwt.secret=94a08da1fecbb6e8b46990538c7b50b2a65d3d4b680d3d3a0c69d80c3b0a7018
jwt.expiration=86400000

# Spring AI Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=gemma4:e2b
